### ISSUE TITLE
difference between de-ud-dev.conllu and de-ud-train.conllu

### ISSUE THREAD

**Issue by simon-clematide** [UniversalDependencies/UD_German#11]
It is quite irritating to me that the same file is present in the repo as dev and train.

What is the reason behind this?

**Comment by jnivre** [comment]
I am afraid I don't understand what you mean. Are you saying the two files contain the same data? Surely, this is not the case.

**Comment by simon-clematide** [comment]
Sorry, my bad, you are right. I messed them up locally.
