### ISSUE TITLE
"zu" as a dependent of an inifite verb in a acl or advcl is connected with "aux" instead of "mark"

### ISSUE THREAD

**Issue by fhennig** [UniversalDependencies/UD_German#3]
[The documentation](http://universaldependencies.org/u/dep/all.html#al-u-dep/mark) for "mark" has a German example, where the infinite verb of an adverbial clause has the "zu" before it, and it is documented that this should be attached with "mark".

[This query](http://bionlp-www.utu.fi/dep_search/query?search=VERB%20%3Eaux%20zu&db=UD_German-v13&case_sensitive=True&hits_per_page=50) shows that "zu" is often attached as "aux", which is wrong.

**Comment by dan-zeman** [comment]
The query searches UD 1.3 but the bug has been fixed in UD 1.4.

**Comment by fhennig** [comment]
Okay, is it possible to query 1.4?

**Comment by dan-zeman** [comment]
That is a question to @fginter . Right now you would get almost the same results by querying the dev branch (see the select-treebank drop-down in the upper left corner), but that will change when the data are converted to v2. At some moment we will hopefully have uploaded the new release into the search engines (PML-TQ currently also has just 1.3).
